import type { Format } from "@/lib/types";

// The library rendered as a menu for the suggestion prompt.
//
// Empty in, empty string out — EXACTLY. The caller omits the whole library
// section when this is empty, which is what makes a zero-format prompt
// identical to a no-library prompt (spec §4). A header with nothing under it
// would both waste tokens and imply to the model that a library exists but
// had nothing worth showing.
export function formatsBlock(formats: Format[], excludeFormatIds: string[] = []): string {
  const excluded = new Set(excludeFormatIds);
  const usable = formats.filter((f) => !excluded.has(f.id));
  if (!usable.length) return "";

  // 'observed' carries a human vouch; 'invented' is only ever a suggestion
  // that happened to stick. A handful of real seeds should outrank a pile of
  // model-derived rows, which is the whole reason origin exists as a column.
  // Array.prototype.sort is stable, so ties keep their incoming order.
  const ranked = [...usable].sort(
    (a, b) => originRank(a.origin) - originRank(b.origin),
  );

  const lines = [
    "FORMAT LIBRARY — post structures already known to work.",
    "Prefer an entry here when one genuinely fits this brand. Invent a new structure only when none does; inventing is a perfectly good outcome, not a failure.",
    "[observed] entries were captured from a real post a human saw work. [invented] entries were generated by this system and kept by a user — weaker evidence, so prefer an observed entry when both fit.",
    "",
  ];
  for (const f of ranked) {
    lines.push(`- id: ${f.id} [${f.origin}]`);
    lines.push(`  Name: ${f.name}`);
    lines.push(`  Structure: ${f.structure}`);
    if (f.why_it_works.trim()) lines.push(`  Why it works: ${f.why_it_works.trim()}`);
    if (f.source_example.trim()) lines.push(`  Source example: ${f.source_example.trim()}`);
    if (f.brand_fit.trim()) lines.push(`  Fits brands that: ${f.brand_fit.trim()}`);
  }
  return lines.join("\n");
}

function originRank(origin: Format["origin"]): number {
  return origin === "observed" ? 0 : 1;
}
